version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      REACT_EDITOR: code
    restart: always

volumes:
  node_modules:
